services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  server:
    build: ./server/
    image: server
    ports:
      - "5000:5000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/app-tester"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
  
  client1:
    build: ./client/
    image: client
    environment:
      - CLIENT_ID=client1
      - MESSAGE=0110111101
    depends_on:
      server:
        condition: service_healthy

  client2:
    build: ./client/
    image: client
    environment:
      - CLIENT_ID=client2
      - MESSAGE=0111010001
    depends_on:
      server:
        condition: service_healthy
