services:

  redis:
    image: redis:latest
    restart: always
  server:
    build: ./server/
    image: server
    ports:
      - "443:443"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f","https://localhost/app-tester"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
  
  client1:
    build: ./client/
    image: client
    environment:
      - CLIENT_ID=client1
      - MESSAGE=3050
    depends_on:
      server:
        condition: service_healthy

  client2:
    build: ./client/
    image: client
    environment:
      - CLIENT_ID=client2
      - MESSAGE=2000
    depends_on:
      server:
        condition: service_healthy
